package battleship;

public class Display extends javax.swing.JFrame {
    
    private float d = -100, timeMomentum = 0.25f;

    private javax.swing.Timer timer;
    
    public Display() {
        initComponents();
        initTimer();
        timer.start();
    }
    
    private void initTimer() {
        this.timer = new javax.swing.Timer(33, (java.awt.event.ActionEvent e) -> {
            battleShip.displayBoards(updateTime());
        });
    }

    private float updateTime() {
        d += timeMomentum;
        if (-100 >= d || d >= 100) timeMomentum *= -1;
        return d;
    }
    
    private void disableButtons() {
        startButton.setEnabled(false);
        resetBoatsButton.setEnabled(false);
        shuffleBoatsButton.setEnabled(false);
        
        carrierButton.setEnabled(false);
        battleshipButton.setEnabled(false);
        destroyerButton.setEnabled(false);
        submarineButton.setEnabled(false);
        patrolButton.setEnabled(false);
        
        resetCarrierButton.setEnabled(false);
        resetBattleshipButton.setEnabled(false);
        resetDestroyerButton.setEnabled(false);
        resetSubmarineButton.setEnabled(false);
        resetPatrolButton.setEnabled(false);
    }
    private void endableButtons() {
        startButton.setEnabled(true);
        resetBoatsButton.setEnabled(true);
        shuffleBoatsButton.setEnabled(true);
        
        carrierButton.setEnabled(true);
        battleshipButton.setEnabled(true);
        destroyerButton.setEnabled(true);
        submarineButton.setEnabled(true);
        patrolButton.setEnabled(true);
        
        resetCarrierButton.setEnabled(true);
        resetBattleshipButton.setEnabled(true);
        resetDestroyerButton.setEnabled(true);
        resetSubmarineButton.setEnabled(true);
        resetPatrolButton.setEnabled(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        battleShip = new battleship.BattleShip();
        startButton = new javax.swing.JButton();
        carrierButton = new javax.swing.JButton();
        battleshipButton = new javax.swing.JButton();
        destroyerButton = new javax.swing.JButton();
        submarineButton = new javax.swing.JButton();
        patrolButton = new javax.swing.JButton();
        resetBoatsButton = new javax.swing.JButton();
        shuffleBoatsButton = new javax.swing.JButton();
        resetCarrierButton = new javax.swing.JButton();
        resetBattleshipButton = new javax.swing.JButton();
        resetDestroyerButton = new javax.swing.JButton();
        resetSubmarineButton = new javax.swing.JButton();
        resetPatrolButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        battleShip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                battleShipMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout battleShipLayout = new javax.swing.GroupLayout(battleShip);
        battleShip.setLayout(battleShipLayout);
        battleShipLayout.setHorizontalGroup(
            battleShipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1500, Short.MAX_VALUE)
        );
        battleShipLayout.setVerticalGroup(
            battleShipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );

        startButton.setText("Start");
        startButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(102, 102, 102)));
        startButton.setFocusable(false);
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        carrierButton.setText("Place Carrier");
        carrierButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(102, 102, 102)));
        carrierButton.setFocusable(false);
        carrierButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carrierButtonActionPerformed(evt);
            }
        });

        battleshipButton.setText("Place Battleship");
        battleshipButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(102, 102, 102)));
        battleshipButton.setFocusable(false);
        battleshipButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                battleshipButtonActionPerformed(evt);
            }
        });

        destroyerButton.setText("Place Destroyer");
        destroyerButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(102, 102, 102)));
        destroyerButton.setFocusable(false);
        destroyerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destroyerButtonActionPerformed(evt);
            }
        });

        submarineButton.setText("Place Submarine");
        submarineButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(102, 102, 102)));
        submarineButton.setFocusable(false);
        submarineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submarineButtonActionPerformed(evt);
            }
        });

        patrolButton.setText("Place Patrol");
        patrolButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(102, 102, 102)));
        patrolButton.setFocusable(false);
        patrolButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patrolButtonActionPerformed(evt);
            }
        });

        resetBoatsButton.setText("Reset All Boats");
        resetBoatsButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(102, 102, 102)));
        resetBoatsButton.setFocusable(false);
        resetBoatsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBoatsButtonActionPerformed(evt);
            }
        });

        shuffleBoatsButton.setText("Shuffle Boats");
        shuffleBoatsButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(102, 102, 102)));
        shuffleBoatsButton.setFocusable(false);
        shuffleBoatsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shuffleBoatsButtonActionPerformed(evt);
            }
        });

        resetCarrierButton.setText("Reset Carrier");
        resetCarrierButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(102, 102, 102)));
        resetCarrierButton.setFocusable(false);
        resetCarrierButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetCarrierButtonActionPerformed(evt);
            }
        });

        resetBattleshipButton.setText("Reset Battleship");
        resetBattleshipButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(102, 102, 102)));
        resetBattleshipButton.setFocusable(false);
        resetBattleshipButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBattleshipButtonActionPerformed(evt);
            }
        });

        resetDestroyerButton.setText("Reset Destroyer");
        resetDestroyerButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(102, 102, 102)));
        resetDestroyerButton.setFocusable(false);

        resetSubmarineButton.setText("Reset Submarine");
        resetSubmarineButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(102, 102, 102)));
        resetSubmarineButton.setFocusable(false);
        resetSubmarineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetSubmarineButtonActionPerformed(evt);
            }
        });

        resetPatrolButton.setText("Reset Patrol");
        resetPatrolButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(102, 102, 102)));
        resetPatrolButton.setFocusable(false);
        resetPatrolButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetPatrolButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(battleShip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(destroyerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(battleshipButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(patrolButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(submarineButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(carrierButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(resetCarrierButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(resetBattleshipButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(resetDestroyerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(resetSubmarineButton, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(resetPatrolButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(startButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(resetBoatsButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(shuffleBoatsButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(battleShip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carrierButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetCarrierButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetBoatsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(shuffleBoatsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(battleshipButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(resetBattleshipButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(resetDestroyerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(destroyerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(submarineButton, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(resetSubmarineButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(startButton, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(patrolButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(resetPatrolButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if (evt.getKeyChar() == 'p') 
            battleShip.printOpponent();
        else if (evt.getKeyChar() == 's') 
            battleShip.saveOpponent();
        
    }//GEN-LAST:event_formKeyPressed

    private void battleShipMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_battleShipMouseReleased
        battleShip.playerClick(evt.getX(), evt.getY());
    }//GEN-LAST:event_battleShipMouseReleased

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        if (battleShip.arePlayerShipsPlaced()) {
            startButton.setText("Started");
            this.disableButtons();
            battleShip.startGame(); 
        } else {
            startButton.setText("Place Ships ...");
        }
    }//GEN-LAST:event_startButtonActionPerformed

    private void battleshipButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_battleshipButtonActionPerformed
        //battleShip.placing(Board.BATTLESHIP);
    }//GEN-LAST:event_battleshipButtonActionPerformed

    private void destroyerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destroyerButtonActionPerformed
        //battleShip.placing(Board.DESTROYER);
    }//GEN-LAST:event_destroyerButtonActionPerformed

    private void patrolButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patrolButtonActionPerformed
        //battleShip.placing(Board.PARTOL);
    }//GEN-LAST:event_patrolButtonActionPerformed

    private void carrierButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carrierButtonActionPerformed
        //battleShip.placing(Board.CARRIER);
    }//GEN-LAST:event_carrierButtonActionPerformed

    private void submarineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submarineButtonActionPerformed
        //battleShip.placing(Board.SUBMARINE);
    }//GEN-LAST:event_submarineButtonActionPerformed

    private void resetCarrierButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetCarrierButtonActionPerformed
        
    }//GEN-LAST:event_resetCarrierButtonActionPerformed

    private void resetBattleshipButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBattleshipButtonActionPerformed
     
    }//GEN-LAST:event_resetBattleshipButtonActionPerformed

    private void resetSubmarineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetSubmarineButtonActionPerformed

    }//GEN-LAST:event_resetSubmarineButtonActionPerformed

    private void resetPatrolButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetPatrolButtonActionPerformed
       
    }//GEN-LAST:event_resetPatrolButtonActionPerformed

    private void shuffleBoatsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shuffleBoatsButtonActionPerformed
        battleShip.shufflePlayerBoard();
    }//GEN-LAST:event_shuffleBoatsButtonActionPerformed

    private void resetBoatsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBoatsButtonActionPerformed
        battleShip.resetPlayerBoard();
    }//GEN-LAST:event_resetBoatsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows Classic".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Display().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private battleship.BattleShip battleShip;
    private javax.swing.JButton battleshipButton;
    private javax.swing.JButton carrierButton;
    private javax.swing.JButton destroyerButton;
    private javax.swing.JButton patrolButton;
    private javax.swing.JButton resetBattleshipButton;
    private javax.swing.JButton resetBoatsButton;
    private javax.swing.JButton resetCarrierButton;
    private javax.swing.JButton resetDestroyerButton;
    private javax.swing.JButton resetPatrolButton;
    private javax.swing.JButton resetSubmarineButton;
    private javax.swing.JButton shuffleBoatsButton;
    private javax.swing.JButton startButton;
    private javax.swing.JButton submarineButton;
    // End of variables declaration//GEN-END:variables
}
